services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.0.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik

  reverse-proxy-https-helper:
    image: alpine
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik

  app:
    image: node:20.11.0-alpine
    working_dir: /usr/src/app
    labels:
      - "traefik.http.routers.app.rule=Host(`app.traefik.me`)"
      - "traefik.http.routers.app-tls.tls.domains[0].main=app.traefik.me"
      - "traefik.http.routers.app-tls.tls.domains[0].sans=app-*.traefik.me"
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    container_name: node-dev-env

volumes:
  certs:
