version: '3.7'

services:
  node-dev-env:
    image: node:20.11.0-alpine
    working_dir: /usr/src/app
    command: >
      sh -c "npm cache clean --force &&
             rm -rf node_modules &&
             npm install &&
             npm run dev"
    ports: 
      - 1234:1234
    volumes:
      - .:/usr/src/app
    container_name: node-dev-env