services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.0.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik
      - certs:/acme

  seaferer:
    image: node:20.11.0-alpine
    working_dir: /usr/src/app
    labels:
      - "traefik.http.routers.seaferer.rule=Host(`saeferer.com`)"
      - "traefik.http.routers.seaferer.entrypoints=https"
      - "traefik.http.routers.seaferer.tls.certresolver=letsencrypt"
    command: >
      sh -c "npm install && npm run build && npm run start"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    container_name: node-dev-env

volumes:
  certs:
